/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WALK = 5;
  /** RegularExpression Id. */
  int TURN = 6;
  /** RegularExpression Id. */
  int LEAP = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int TURNTO = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int GET = 11;
  /** RegularExpression Id. */
  int GRAB = 12;
  /** RegularExpression Id. */
  int LETGO = 13;
  /** RegularExpression Id. */
  int NOP = 14;
  /** RegularExpression Id. */
  int JUMP = 15;
  /** RegularExpression Id. */
  int DEFVAR = 16;
  /** RegularExpression Id. */
  int DEFPROC = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int TIMES = 22;
  /** RegularExpression Id. */
  int FACING = 23;
  /** RegularExpression Id. */
  int CAN = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int SOUTH = 26;
  /** RegularExpression Id. */
  int NORTH = 27;
  /** RegularExpression Id. */
  int EAST = 28;
  /** RegularExpression Id. */
  int WEST = 29;
  /** RegularExpression Id. */
  int FRONT = 30;
  /** RegularExpression Id. */
  int BACK = 31;
  /** RegularExpression Id. */
  int RIGHT = 32;
  /** RegularExpression Id. */
  int LEFT = 33;
  /** RegularExpression Id. */
  int NUM = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int NAME = 36;
  /** RegularExpression Id. */
  int CHAR = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"walk\"",
    "\"turn\"",
    "\"leap\"",
    "\"Pick\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letgo\"",
    "\"nop\"",
    "\"jump\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"times\"",
    "\"facing\"",
    "\"can\"",
    "\"not\"",
    "\"south\"",
    "\"north\"",
    "\"east\"",
    "\"west\"",
    "\"front\"",
    "\"back\"",
    "\"right\"",
    "\"left\"",
    "<NUM>",
    "<DIGIT>",
    "<NAME>",
    "<CHAR>",
    "\" { \"",
    "\";\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\":\"",
  };

}
